[profile.default]
src = "src"
test = "foundry-tests"
out = "artifacts"
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@nomicfoundation/=node_modules/@nomicfoundation/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
